---
title: "compare_outputs, 01_benchmark_2018_find_scripts_outputs"
author: "Kirsten Birch Håkansson, DTU Aqua"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(tidyr)

path1 <- "C:/Users/kibi/OneDrive - Danmarks Tekniske Universitet/gits/spr.27.3a4_commercial_catch/output/00_canum_weca_in_present_model/"
path2 <- "C:/Users/kibi/OneDrive - Danmarks Tekniske Universitet/gits/spr.27.3a4_commercial_catch/output/01_canum_weca_from_benchmark/Sprat-div-4_plus_IIIa_FINAL/"
path3 <- "C:/Users/kibi/OneDrive - Danmarks Tekniske Universitet/gits/spr.27.3a4_commercial_catch/output/03_benchmark_2018_files_from_anna/"
path4 <- "C:/Users/kibi/OneDrive - Danmarks Tekniske Universitet/gits/spr.27.3a4_commercial_catch/output/01_benchmark_2018_20181005_run/"
path5 <- "C:/Users/kibi/OneDrive - Danmarks Tekniske Universitet/gits/spr.27.3a4_commercial_catch/output/01_benchmark_2018_2025_rerun/"
path6 <- "C:/Users/kibi/OneDrive - Danmarks Tekniske Universitet/gits/spr.27.3a4_commercial_catch/output/05_files_from_anna_20250725/"


```

# Canum

```{r}
canum_present <- read.csv(paste0(path1, "canum.csv"), sep = ";", header = T)
canum_present$type <- "present canum"
canum_present_t <- gather(canum_present, key = age, value = no, , -year, -season, -type)
canum_present_t$age <- substr(canum_present_t$age, 2, 2)

canum <- read.csv(paste0(path6, "July_to_june_quarterly_catch_in_numbers_and_mean_weight_benchmark_IV_no_Q2_2019_in2020.csv"), sep = ",")
canum$season <- canum$quarter
canum$type <- "From Anna 2018"
names(canum)
canum <- select(canum, year, season, type, n0, n1, n2, n3)
canum_t <- gather(canum, key = age, value = no, , -year, -season, -type)
canum_t$age <- substr(canum_t$age, 2, 2)


comb <- bind_rows(canum_present_t, canum_t)
```

```{r}

ggplot(data = comb, aes(x = year, y = no, col = type)) +
  # geom_bar(stat = "identity", position = "dodge") +
  geom_line() +
  facet_grid(age~season, scale = "free_y") +
  labs(title = "Number at age per season and year")
```

# WECA

```{r}
canum_present <- read.csv(paste0(path1, "weca.csv"), sep = ";", header = T)
canum_present$type <- "present weca"
canum_present_t <- gather(canum_present, key = age, value = mw, , -year, -season, -type)
canum_present_t$age <- substr(canum_present_t$age, 3, 3)
canum_present_t$season <- as.numeric(canum_present_t$season)
canum_present_t$year <- as.numeric(canum_present_t$year)

canum <- read.csv(paste0(path5, "July_to_june_quarterly_catch_in_numbers_and_mean_weight_benchmark_IV.csv"), sep = ",")
canum$season <- canum$quarter
canum$type <- "From Anna 2018"
names(canum)
canum <- select(canum, year, season, type, mw0, mw1, mw2, mw3)
canum_t <- gather(canum, key = age, value = mw, , -year, -season, -type)
canum_t$age <- substr(canum_t$age, 3, 3)


comb <- bind_rows(canum_present_t, canum_t)
```

```{r}

ggplot(data = comb, aes(x = year, y = mw, col = type)) +
  # geom_bar(stat = "identity", position = "dodge") +
  geom_line() +
  facet_grid(season~age, scale = "free_y") +
  labs(title = "Number at age per season and year")
```

